### ISSUE TITLE
No point in adding CNAMEs if AAD Premium?

### ISSUE THREAD

**Issue by o-l-a-v** [MicrosoftDocs/memdocs#1949] opened 2021-08-31 22:18 UTC
Are there no benefits what so ever in adding the CNAMEs if one already have Azure AD Premium license(s) and automatic enrollment enabled on the tenant?

Yes or no: Please specify this in the documentation.

(admin edit: including article metadata for proper tracking)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f1e311c-c5ff-1c68-028d-e4fddda23324
* Version Independent ID: 1d2174e5-8984-8d9c-34c5-dfbcc619b410
* Content: [Set up enrollment for Windows devices by using Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/enrollment/windows-enroll)
* Content Source: [memdocs/intune/enrollment/windows-enroll.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/enrollment/windows-enroll.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by aczechowski** [comment] 2021-09-01 17:34
Hi @o-l-a-v, can you clarify which article you're referencing? We have 20 articles in this repo that discuss CNAMEs. 😄

**Comment by o-l-a-v** [comment] 2021-09-01 17:57
> Hi @o-l-a-v, can you clarify which article you're referencing? We have 20 articles in this repo that discuss CNAMEs. 😄 

This one:

https://docs.microsoft.com/en-us/mem/intune/enrollment/windows-enroll

**Comment by lenewsad** [comment] 2023-06-26 22:55
Hi @o-l-a-v, thanks for reaching out to the Microsoft Intune documentation team with your question. I can confirm that CNAMEs are not required if automatic enrollment is enabled and you have an Azure AD Premium license.  Unfortunately, at this time, I am unable to confirm if there is any additional benefit to having CNAMEs in that kind of environment. I'm staying in touch with the product team and will be sure to update the article if it's warranted. 

I want to redirect you to another support channel where you can ask questions to the Microsoft Intune community and get answers from our Microsoft MVPs and other industry professionals: [Microsoft Intune tech community](https://techcommunity.microsoft.com/t5/microsoft-intune/bd-p/Microsoft-Intune).  

Thanks again for your dedication to the Intune docs. Because this issue doesn't require a fix to documentation, I am closing it.

**Closed by lenewsad** 2023-06-26 22:55 UTC
Labels: doc-enhancement, microsoft-intune/svc, enrollment/subsvc, in-progress, pm, product-question, Pri3
