### ISSUE TITLE
Re-install iOS VPP required app

### ISSUE THREAD

**Issue by kevintaber** [MicrosoftDocs/memdocs#2112] opened 2021-10-18 21:45 UTC
If an end user removes a _required_ iOS app (VPP user or device licensed), how does an admin re-install the app?

A common headache I've faced in particular is regarding ADE iOS devices. Company Portal is installed via VPP device license, and  the end user deletes the app. I have no way to re-install it and that app in particular can't be downloaded from the App Store. It's not compatible with ADE.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f7ad786b-eac9-7979-9509-25e05673b35a
* Version Independent ID: 42d279ce-086f-be9f-821f-53d7100fa838
* Content: [Assign apps to groups in Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/apps-deploy)
* Content Source: [memdocs/intune/apps/apps-deploy.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/apps-deploy.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by msbemba** [comment] 2022-03-15 16:45
@kevintaber Thank you for your feedback. Sorry about the delay in getting back to you. 

Looks like you have already added Company Portal to the VPP token. To ensure that Company Portal continues to be updated after enrollment, make sure that you've configured an app deployment in Intune (In Endpoint Manager select Apps > All apps > Add). This way it gets updated. This data is available in the document.

I'd recommend you open a support case directly with the Microsoft support team and someone would be able to assist you.

Hope this helps!

Thanks
Sri

**Comment by msbemba** [comment] 2022-03-15 17:29
@kevintaber Thank you for your response. You are right, It should let you use that option and not let users uninstall. That is the way to restrict users from uninstalling the app.

Looks like it is either a bug or it not working by design. In both cases, I'd recommend you contacting support as the 1st option as they will be able to collect logs and escalate or file a bug as and when needed. 

Thanks
Sri

**Comment by yogkumgit** [comment] 2022-03-16 06:18
@msbemba Thank you very much for the contribution and sharing this explanation. @kevintaber Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Closed by yogkumgit** 2022-03-16 06:18 UTC
Labels: microsoft-intune/svc, /tech, Pri1, support-request, apps/subsvc
