### ISSUE TITLE
Which type of policy to choose?

### ISSUE THREAD

**Issue by rasldasl** [MicrosoftDocs/memdocs#1644] opened 2021-05-26 20:11 UTC
When an app (such as Outlook) has the desired configuration available in both Managed Devices and Managed Apps do you lose anything/gain anything with one over the other? Is there a conflict if you have both applied to the same device?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f99adcae-3960-b5f8-efd3-1603490519c7
* Version Independent ID: d9164111-640b-d88c-3dad-661179e5114e
* Content: [App configuration policies for Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/app-configuration-policies-overview)
* Content Source: [memdocs/intune/apps/app-configuration-policies-overview.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/app-configuration-policies-overview.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by yogkumgit** [comment] 2022-02-27 12:02
@rasldasl Thank you very much for reporting the issue . Considering the nature of the issue please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Closed** 2022-02-27 12:02 UTC
Labels: microsoft-intune/svc, /tech, Pri1, support-request, apps/subsvc

**Comment by stmahoney** [comment] 2022-04-06 17:46
I worked with a customer with this same question and we found that when a User is targeted for both the Managed App and Managed Device with different configurations the Managed App configuration would always win.  Having the same configuration did not seem to have an issue, only when the settings would differ between the two channels.  Working with MS Support it was determined this behavior was by design.  It would be good to have the documentation updated for a note indicating this expected behavior.
