### ISSUE TITLE
App entitlements for wrapping 

### ISSUE THREAD

**Issue by Dzysta** [MicrosoftDocs/memdocs#291] opened 2020-05-25 09:42 UTC
Hi, 

Documents says that he application needs to have appropriate entitlements in order to be wrapped but there is no link or document what exactly it should be

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c369fd67-8df1-6480-b04d-701e3bd9a689
* Version Independent ID: 268bf40f-9b4c-79ff-d51d-069652c7832e
* Content: [Wrap iOS apps with the Intune App Wrapping Tool](https://docs.microsoft.com/en-us/mem/intune/developer/app-wrapper-prepare-ios)
* Content Source: [memdocs/intune/developer/app-wrapper-prepare-ios.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/developer/app-wrapper-prepare-ios.md)
* Service: **microsoft-intune**
* Sub-service: **developer**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by Kyle-Reis** [comment] 2020-05-25 12:57
This is a duplicate of this issue from the app wrapping tool release repo: https://github.com/msintuneappsdk/intune-app-wrapping-tool-ios/issues/42

**Comment by Erikre** [comment] 2020-06-04 21:27
Closing because this issue has been addressed in the above linked issue.

**Closed by Erikre** 2020-06-04 21:27 UTC
Labels: /tech, Pri2, assigned-to-author, developer/subsvc, microsoft-intune/svc, triaged
