### ISSUE TITLE
IMEI not supported across all platforms?

### ISSUE THREAD

**Issue by SteveBurkettNZ** [MicrosoftDocs/memdocs#685] opened 2020-08-26 22:04 UTC
Under section 'Identify corporate-owned devices with IMEI or serial number', for IMEI it's listing all platforms as Not Supported. This doesn't sound correct?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bcd313b3-e225-849a-def5-8a32a08a92e9
* Version Independent ID: 917b6190-a8bd-f55d-3e71-f403a395721f
* Content: [Add corporate identifiers to Intune](https://docs.microsoft.com/en-us/mem/intune/enrollment/corporate-identifiers-add#identify-corporate-owned-devices-with-imei-or-serial-number)
* Content Source: [memdocs/intune/enrollment/corporate-identifiers-add.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/enrollment/corporate-identifiers-add.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by JeremyTBradshaw** [comment] 2020-12-23 14:00
@SteveBurkettNZ @ErikjeMS This issue is 100% accurate.  I know for certain that IMEI number DOES result in Android Enterprise - Work Profile ("personally-owned" edition of Work profile) being marked as "Corporate-owned".  I can confirmed from my testing that unfortunately IMEI number doesn't need to be present for the Fully Managed enrolled devices to be marked as corporate.

I'm using this comment as my location of choice to gripe about two things related to this:

1. Regarding Android Enterprise Work Profile (the "personal" version, not COPE), it seems a little misleading to label this enrollment method as "Personally-owned" when that is not what Google themselves call it.  This bad decision is worse, when companies pre-load IMEI's and then enroll devices this way.  This results in the OS showing up with the terminology "personally-owned", yet the device properties in Intune/Endpoint will show up that Ownership = "Corporate" (again, because IMEI DOES work to make this type of enrolled device deemed as Corporate-owned, contrary to this docs page, which is why @SteveBurkettNZ  opened this issue).

2. The Android Enterprise Fully Managed enrollment token is not revocable like Dedicated / COPE, yet there's no way to block users from enrolling this kind of a device, and so this leads to the question - why is this token not revocable?  It's a gap and an inconsistency.

I'll stop there, but Intune/Endpoint has got to be called out for this stuff.  It's not very "enterprise" friendly when it's riddled with loop holes.  These issues I'm raising are not the kind of issues that I should be sent to MS Support or UserVoice for.  I'll raise them on Tech Community, but they might as well be raised internally as a result of me having raised them here.

**Comment by ErikjeMS** [comment] 2021-02-16 18:43
The documentation team hasn’t been able to find an answer for this issue. If this is still an issue for you can try any of the following: 
- Open a support ticket by following the steps here: [How to get support for Microsoft Intune](https://docs.microsoft.com/intune/get-support). 
- Post on [Microsoft Intune forums](https://social.technet.microsoft.com/Forums/en-US/home?forum=microsoftintuneprod). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.   
- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.   
I'm closing this issue as there's nothing actionable for docs at this time.

**Closed by ErikjeMS** 2021-02-16 18:43 UTC
Labels: /tech, Pri2, assigned-to-author, doc-bug, enrollment/subsvc, microsoft-intune/svc, triaged
