### ISSUE TITLE
No support for Windows 10?

### ISSUE THREAD

**Issue by Canis-Lupis** [MicrosoftDocs/memdocs#2466] opened 2022-02-21 21:15 UTC
[Enter feedback here]
This seems like an obvious miss; can't remote lock Windows 10?  Why? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c79f5e46-0615-682c-0368-5a14cfa738e7
* Version Independent ID: 08094776-efc7-d7b1-0b82-0aee1dac5634
* Content: [Lock devices with Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/remote-actions/device-remote-lock)
* Content Source: [memdocs/intune/remote-actions/device-remote-lock.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/remote-actions/device-remote-lock.md)
* Service: **microsoft-intune**
* Sub-service: **remote-actions**
* Technology: ****
* GitHub Login: @Smritib17
* Microsoft Alias: **smbhardwaj**

**Comment by msbemba** [comment] 2022-04-11 06:02
@Canis-Lupis Thank you for your feedback. This feature is not available currently on the windows 10 desktop and this is by design. You can post this as a feature request (On our main feedback portal -https://feedbackportal.microsoft.com/) to our dev/product team and they will be able to respond back to you with the reasons why it is not supported yet and if they have plans to release this. 

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment] 2022-04-16 03:53
@Canis-Lupis Thank you very much for your kind feedback. Considering your valuable feedback, please log this issue as advised. Here we are limited to documentation fixes and improvements only. Concerning team will evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.

**Closed** 2022-04-16 03:53 UTC
Labels: microsoft-intune/svc, /tech, product-feedback, remote-actions/subsvc, Pri2
