### ISSUE TITLE
Autopilot reset requires bitlocker recovery key at boot - BitLocker

### ISSUE THREAD

**Issue by SrDirko** [MicrosoftDocs/memdocs#2919] opened 2022-07-07 13:12 UTC
We've been testing Autopilot reset. It is requesting bitlocker recovery key after boot. Please document this and the resolution. The reset fails if bitlocker recovery key is not entered.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8411fd84-8a1d-28e6-1535-30143be7ede2
* Version Independent ID: 4e5ecbe1-aa9b-cfa0-7b67-1ac1dcb0c465
* Content: [Windows Autopilot Reset](https://docs.microsoft.com/en-us/mem/autopilot/windows-autopilot-reset)
* Content Source: [memdocs/autopilot/windows-autopilot-reset.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/autopilot/windows-autopilot-reset.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by frankroj** [comment] 2023-04-29 00:06
Thank you for the feedback @SrDirko. I apologize for the time it took to get back to you regarding this feedback item. I have tested Autopilot Reset with Windows 11 22H2 and an Azure AD joined device and I could not reproduce the issue, whether using remote or local Autopilot Reset. The reset completes on a BitLockered device without ever asking for the key. It may be that the issue has been resolved since you first filed this feedback.

If you are still having issues, I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this issue:

- Post to [Microsoft](https://learn.microsoft.com/answers/tags/415/intune). These are moderated by community members who are very experienced, knowledgeable, and helpful.
- Use [Windows Autopilot support information](https://support.microsoft.com/windows) to find your available support options.
- Contact your Microsoft Unified Support team, such as a Customer Engineer or Customer Success Account Manager.

I'm closing this issue as there's nothing actionable for docs at this time.

**Closed by frankroj** 2023-04-29 00:06 UTC
Labels: Pri1, w10/prod, windows/tech

**Comment by BurritoBeast** [comment] 2023-07-20 21:00
I am seeing the same issue. As a school district we would like to turn on bitlocker & encrypt our student devices. But with 9000 students having to enter this key anytime we would need to reset a machine would be time consuming. It would be nice to have a way to bypass this although I get what I'm asking would actually create an issue.

**Comment by frankroj** [comment] 2023-07-24 19:41
@BurritoBeast can you please open a case with support to further dig into the issue. As I mentioned above, I wasn't able to reproduce the issue in my lab. There may be additional variables and factors in play that cause this scenario. Support should be able to help you figure out why the issue is occurring. Thank you.

**Comment by MDMALL** [comment] 2023-10-25 13:35
Hi @frankroj,

I am working for a client where we have not yet migrated to Win 11 and all devices are Win 10. We have HP fleet and while doing reset we are experiencing the same issue where each device is asking for Bitlocker key. Is there any change or any update from MS.
Can you please guide me what could be possible cause of it.

**Comment by frankroj** [comment] 2023-10-25 13:50
Hello @MDMALL. Thank you for the feedback. However, this isn't really a support channel. This feedback is more for existing documentation. I would recommend you open a support case if you need additional help.

**Comment by TassieTrooper** [comment] 2024-01-09 11:11
We have just started to have this problem. Over 1000 device and seldom do we Autopilot reset but the last time I captured tehe image, which had to redo the WinRE with additional drivers, I am not getting the request for the BitLocker key. So is there something drive side within WinRE that triggers this? I will have to restore the previous image and check.
