### ISSUE TITLE
Inconsistent naming conventions and confusing information around discovered apps on Android devices.

### ISSUE THREAD

**Issue by zlDev** [MicrosoftDocs/memdocs#1229] opened 2021-01-17 17:20 UTC
Hi

I'm struggling to understand which Android enrolment profile allows admins to see personal apps under Discovered Apps tab when selecting a device from a list of enrolled devices.

There are 4 enrolment profile types for Android Enterprise.

1. Personally-owned devices with work profile
2. Corporate-owned dedicated devices
3. Corporate-owned, fully managed user devices
4. Corporate-owned devices with work profile

In the section "Details of discovered apps" it says the following under the "_Android Enterprise_" row under the "_For company-owned devices_" column:

_Only apps installed in the Android Enterprise fully managed work profile._

Firstly, "Android Enterprise fully managed work profile" is not one of those 4 enrolment scenarios. I would appreciate if someone rewords this to align with the naming conventions in the Intune portal.

Secondly, Does this means that apps are visible under enrolment profile 3 since it references "_fully managed_" or under 4 since it references "_work profile_"

Then in the notes section, it makes it even more confusing by making this contradicting statement:

"_Android Enterprise Fully Managed and Dedicated do not display discovered apps._"

It is not clear in which of those 4 scenarios possible to see personal apps installed on devices with ownership type "corporate". 

Apologies if this sounds like a rant :), I've tried reading this couple of times and still can't make sense of it. 

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2f41921-6680-75b6-5b95-55327279861a
* Version Independent ID: a0178c17-b82b-b762-49f6-17e2abcbd775
* Content: [Discovered apps - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/app-discovered-apps)
* Content Source: [memdocs/intune/apps/app-discovered-apps.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/app-discovered-apps.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by Erikre** [comment] 2021-02-18 23:30
Thanks for the feedback. I'm tracking this issue using an internal work item and I'm requesting feedback from the product team. Once I have confirmed the change, I'll update the topic. If you have continue to have questions related to this issue, we want to make sure your questions get to the right people that can help. There are a couple of options available to provide the best level of support for this:

- Post your issue on [Microsoft Intune forums](https://social.technet.microsoft.com/Forums/en-US/home?forum=microsoftintuneprod). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.

- Use [How to get support for Microsoft Intune](https://docs.microsoft.com/intune/get-support) to open a case with professional support.

- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.

Please use the above channels if you don't already have a solution. Because I'm tracking any doc updates based on an internal work item, I'm closing this GitHub issue. Thanks

**Closed by Erikre** 2021-02-18 23:30 UTC
Labels: /tech, Pri2, apps/subsvc, microsoft-intune/svc, pm, tracking-as-internal-work-item
