### ISSUE TITLE
The Windows 10 IoT Enterprise LTSC 2019" is supported for Autopilot ?

### ISSUE THREAD

**Issue by MPICOLLET** [MicrosoftDocs/memdocs#1410] opened 2021-03-16 09:19 UTC
Hello,

You say : "Autopilot isn't supported on IoT Core devices, and there are currently no plans to add this support. Autopilot is supported on Windows 10 IoT Enterprise **SAC** devices. Autopilot is supported on Windows 10 Enterprise **LTSC** 2019 and above; it isn't supported on earlier versions of LTSC."

But the "Windows 10 **IoT** Enterprise LTSC 2019" is supported ?

M.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1b12323-90a7-00db-16ea-8daec3a9306f
* Version Independent ID: 0c1a1865-cf35-0862-b328-02371bb30441
* Content: [Windows Autopilot FAQ](https://docs.microsoft.com/en-us/mem/autopilot/autopilot-faq)
* Content Source: [memdocs/autopilot/autopilot-faq.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/autopilot/autopilot-faq.md)
* Product: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by aczechowski** [comment] 2022-08-23 18:46
I think this issue is a duplicate of https://github.com/MicrosoftDocs/memdocs/issues/2981, so I'm closing it.

**Closed by aczechowski** 2022-08-23 18:46 UTC
Labels: Pri2, w10/prod
