### ISSUE TITLE
Azure MFA SMS code not working during ADE setup assistant when SIM card is used on pre-ADE device 

### ISSUE THREAD

**Issue by JimmyLS** [MicrosoftDocs/memdocs#2201] opened 2021-11-11 00:00 UTC
The article mentioned Azure MFA works in Setup Assistant when using ADE. 

![image](https://user-images.githubusercontent.com/25541899/141212283-1d4279c9-ecf3-449c-b67c-ba92c4ce06d9.png)

However, based on our testing if the SIM card (the phone number used to register MFA) is used on the pre-ADE device, and if the default MFA method is SMS code, user will never receive SMS code when it's prompted to perform MFA. This is not a MFA problem because it's working other places. 

If that's by-designed, please add a note in this article to tell customer and make more accurate statement. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd130267-c54b-41e3-d534-831d4a86bae6
* Version Independent ID: bdfa7eca-a356-3dde-7643-9a759f952007
* Content: [Enroll iOS/iPadOS devices by using ADE - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/enrollment/device-enrollment-program-enroll-ios)
* Content Source: [memdocs/intune/enrollment/device-enrollment-program-enroll-ios.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/enrollment/device-enrollment-program-enroll-ios.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by msbemba** [comment] 2022-03-24 10:19
@JimmyLS Thank you for your feedback. As mentioned  Azure MFA works in Setup Assistant when using ADE. The problem statement is not by design, We usually refer customers to provide such feedback on our main feedback portal. In this case, I have raised the feedback Myself and this will be handled by the dev/product team. Feedback portal Link -https://feedbackportal.microsoft.com/feedback/idea/d8022fbd-5bab-ec11-a81c-0022485066fe

You can upvote and add a comment to the feedback if need be.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment] 2022-03-24 15:19
@msbemba Thank you very much for the contribution and sharing this explanation. @JimmyLS Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Closed by yogkumgit** 2022-03-24 15:19 UTC
Labels: microsoft-intune/svc, enrollment/subsvc, /tech, Pri1, product-feedback
