### ISSUE TITLE
Ready vs Ready with Remediation Requirements

### ISSUE THREAD

**Issue by niolmstead** [MicrosoftDocs/memdocs#1521] opened 2021-04-14 12:21 UTC
The documentation seems to indicate that devices can be ready for Pilot or Production with either Ready or Ready with Remediation in Desktop Analytics.  It is not clear that in order for devices to be upgraded in ConfigMgr that they need to be 'Ready' and not 'Ready with Remediation'.  Since we can use a Task Sequence to upgrade devices and remediate those issues as part of that process it makes sense that both would work, if that is not the case it would be helpful to more clearly define the differences and the requirement for the Remediation to take place before ConfigMgr can upgrade the device.  Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7d823db-5332-c5cc-9f04-6849edcaf7d5
* Version Independent ID: 5a85c1d0-d940-c3f5-a98d-821f58e6e1b4
* Content: [How to deploy to production - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/desktop-analytics/deploy-prod?source=docs)
* Content Source: [memdocs/configmgr/desktop-analytics/deploy-prod.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/desktop-analytics/deploy-prod.md)
* Product: **configuration-manager**
* Technology: **configmgr-analytics**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment] 2021-04-14 17:19
Hi @niolmstead, this is a duplicate of #1432. I'll be responding with more info to that issue shortly

**Closed by aczechowski** 2021-04-14 17:19 UTC
Labels: Pri2, configmgr-analytics/tech, configuration-manager/prod, duplicate
