### ISSUE TITLE
schema ownership for MPS

### ISSUE THREAD

**Issue by rdoloto** [MicrosoftDocs/memdocs#1088] opened 2020-12-04 14:33 UTC
If you  are using multiple management points the schema owners or rights do not get propagated to any recovery Schema in CM DB. you have to manually add these for each management point th
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d362145-5048-abf3-fad0-1b6c25f76447
* Version Independent ID: 988e83fa-54da-9bf6-ba19-98006f0043a2
* Content: [Deploy BitLocker management - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/protect/deploy-use/bitlocker/deploy-management-agent)
* Content Source: [memdocs/configmgr/protect/deploy-use/bitlocker/deploy-management-agent.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/protect/deploy-use/bitlocker/deploy-management-agent.md)
* Product: **configuration-manager**
* Technology: **configmgr-protect**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment] 2020-12-05 02:01
Thanks @rdoloto for taking the time to provide feedback on Configuration Manager! After discussing with the engineering team, it sounds like a product bug, so I want to make sure it gets directly into their hands. Fortunately, we've got dedicated channels for that very purpose. :) See the [Product feedback](https://docs.microsoft.com/mem/configmgr/core/understand/product-feedback) section in our docs. I think it’s important that you submit it directly, because that allows you to receive notifications and more closely monitor the progress. I'm closing this issue as there's nothing actionable for docs at this time.

When you file a frown, please also include detailed steps to reproduce the issue, and detailed steps to workaround. The engineering teams wants to better understand the issue, and how the can automatically fix it.

**Closed by aczechowski** 2020-12-05 02:01 UTC
Labels: configmgr-protect/tech, configuration-manager/prod, triaged
