### ISSUE TITLE
Documentation Add-on to describe SMSMPLIST property

### ISSUE THREAD

**Issue by Fusillier** [MicrosoftDocs/memdocs#2015] opened 2021-09-24 16:26 UTC
SMSMP
Specifies list of management points for the Configuration Manager client to use.

 Important

If the management point only accepts client connections over HTTPS, prefix the management point name with https://.

Examples:

CCMSetup.exe SMSMPLIST=smsmp01.contoso.com;msmp02.contoso.com

CCMSetup.exe SMSMPLIST=https://smsmp01.contoso.com;https://smsmp02.contoso.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3f3e45d-8f9d-aa5a-8b6a-d8c51c50d11e
* Version Independent ID: f5305fc4-894b-19dd-26c8-6f90901d4b1e
* Content: [Client installation parameters and properties - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/clients/deploy/about-client-installation-properties)
* Content Source: [memdocs/configmgr/core/clients/deploy/about-client-installation-properties.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/clients/deploy/about-client-installation-properties.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment] 2021-10-19 17:25
Closing as duplicate of internal tracking item (10060121)

**Closed by aczechowski** 2021-10-19 17:25 UTC
Labels: duplicate, Pri1, tracking-as-internal-work-item, configuration-manager/prod, configmgr-client/tech
