### ISSUE TITLE
Add a note deleted apps from Client apps list

### ISSUE THREAD

**Issue by rockon908** [MicrosoftDocs/memdocs#2750] opened 2022-05-05 17:05 UTC
Can we add a note in the delete apps section that:

If the app is deleted from Client apps in Endpoint manager, they won't be able to push it back again (when it's mentioned as unpublished)

And also mention that they will need a APK with new package name as the older one gets "stuck"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5a2b8f0-f2a0-f4d6-94d9-06e6d9632f59
* Version Independent ID: 8c8d89cf-9ed7-bb02-2439-e7ce9bb03f0c
* Content: [Add and assign Managed Google Play apps to Android Enterprise devices - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/apps-add-android-for-work)
* Content Source: [memdocs/intune/apps/apps-add-android-for-work.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/apps/apps-add-android-for-work.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by msbemba** [comment] 2022-05-19 16:50
@rockon908 Thank you for your feedback. By design, it should allow you to push it back once it becomes unpublished. I was able to test it with an app. This sounds like a bug than a document change, hence request you to contact support via the need help section on the admin center, so that a support engineer can help you fix this or raise a bug with the product group.

Thanks
Sri

**Comment by yogkumgit** [comment] 2022-05-20 04:15
@msbemba Thank you very much for the contribution and sharing this explanation. @rockon908 Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Closed by yogkumgit** 2022-05-20 04:15 UTC
Labels: microsoft-intune/svc, /tech, Pri1, support-request, apps/subsvc
