### ISSUE TITLE
Steps missing for in-place OS upgrade of Server 2012 R2 to 2016/2019 for distribution points.

### ISSUE THREAD

**Issue by SMSAgentSoftware** [MicrosoftDocs/memdocs#879] opened 2020-10-14 15:00 UTC
Can you please update this document to provide the additional steps required when performing an in-place OS upgrade on distribution points from Windows Server 2012 R2. Following the current documentation I was led to believe upgrading our 2012 R2 DPs to 2019 would go smoothly, however I encountered issues that others have also reported and blogged about that are not even mentioned here, including:

- The ConfigMgr client was broken after upgrade. Specifically there were WMI-related issues. The SMS Agent host service was not started and would not start. Reinstalling the ConfigMgr client failed with the error "MSI: Setup was unable to compile the file DiscoveryStatus.mof The error code is 80041002" To fix it, I had to run "mofcomp ...\Program Files\Microsoft Policy Platform\ExtendedStatus.mof" and then run the "Configuration Manager Health Evaluation" scheduled task to self-remediate the WMI issues.

- The ROOT\SCCMDP namespace was missing from WMI. This essentially broke the distribution point functionality. To fix that, I had to run "mofcomp ...\sms\bin\smsdpprov.mof" to recreate the WMI namespace, and then I had to run a SQL query to find the list of packages distributed to that DP and build some PowerShell code to add those packages back into WMI. This has been documented by others, eg https://sccmnotes.wordpress.com/2019/11/08/upgraded-sccm-distribution-point-and-sccmdp-namespace-is-missing/. Finally I had to run the content validation scheduled task to re-validate the package content.

I did not encounter these issues when doing an in-place OS upgrade from Server 2016 to 2019, only from Server 2012 R2 to 2019.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d966b168-c00d-bdd5-0839-ec95bebbac43
* Version Independent ID: 7ef0960d-3f56-8534-7e98-34fa47f0cd7c
* Content: [Upgrade on-premises infrastructure - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/servers/manage/upgrade-on-premises-infrastructure)
* Content Source: [memdocs/configmgr/core/servers/manage/upgrade-on-premises-infrastructure.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/servers/manage/upgrade-on-premises-infrastructure.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment] 2020-10-16 17:11
Hi @SMSAgentSoftware, sorry that you had issues with this. I checked with our engineering team who handles this sort of "app compatibility" and they just recently completed a test pass for the same scenario and could not reproduce the issue. There are a couple of options available to provide the best level of support for this issue:
- Post on [Configuration Manager forums](https://docs.microsoft.com/answers/products/mem). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://aka.ms/cmcbsupport) to search for the issue, or open a case with professional support.
- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.
I'm closing this issue as there's nothing actionable for docs at this time.

**Closed by aczechowski** 2020-10-16 17:11 UTC
Labels: Pri2, configmgr-core/tech, configuration-manager/prod, support-request, triaged

**Comment by SMSAgentSoftware** [comment] 2020-10-16 20:59
Hey, interesting that you can’t reproduce it - I’ve encountered the exact same issues on all 7 of the 2012 R2 servers I’ve upgraded so far. Clearly I’m not alone either, as the blog I linked above indicates.
I find the Docs a bit misleading here since the upgrade scenario is supposedly ‘supported’ yet they don’t mention anything about these issues which makes you think the upgrade will be successful, then when it isn’t I have to figure out how to get things working again.
I did raise a support case with Microsoft already and their only suggestions were 1. do a site reset, which isn’t viable when you have many servers to update, or 2. (apparently unsupported) fix it by doing exactly what I’ve already described.
If you can’t at least put a note it in the Docs, I’ll blog it myself - just trying to help other people here after all.

Trevor

**Comment by aczechowski** [comment] 2020-10-16 22:27
I'll check back with the engineers if they have a suggested process to fix the issue. Getting a support case escalated for better root cause analysis would be best, but could also be costly to you if there really isn't a bug and it's some environmental aspect. Alternatively, file a frown with more details (logs, versions, reference to case ID, etc.). That bug might just get closed as "no repro" but would at least have the bug to track it.
