### ISSUE TITLE
Convert Devices not supported for Hybrid AD Join -> AAD Join verbiage

### ISSUE THREAD

**Issue by Matgard** [MicrosoftDocs/memdocs#2181] opened 2021-11-04 17:45 UTC
The verbiage "Converting all targeted devices to Autopilot is not supported for transforming a hybrid Azure AD device into a Azure AD Autopilot device" is not consistent with the main doc for the feature to Convert Devices to Autopilot. This either needs to be qualified for just Autopilot for Existing Devices, removed, or added to the main doc regarding the feature: https://docs.microsoft.com/en-us/mem/autopilot/automatic-registration

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4cb0ab9e-0902-8c43-5cb9-8ade31c88f5f
* Version Independent ID: d30aebff-dc9c-bcd9-2ffd-c7158da55026
* Content: [Windows Autopilot Deployment for existing devices](https://docs.microsoft.com/en-us/mem/autopilot/existing-devices)
* Content Source: [memdocs/autopilot/existing-devices.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/autopilot/existing-devices.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by aczechowski** [comment] 2021-11-04 17:49
Thanks @Matgard for the feedback, I'm going to consider it a duplicate of #2175

**Closed by aczechowski** 2021-11-04 17:49 UTC
Labels: duplicate, Pri1, w10/prod, windows/tech
