### ISSUE TITLE
Computer restart in v2002

### ISSUE THREAD

**Issue by ChadSimmons** [MicrosoftDocs/memdocs#281] opened 2020-05-21 21:12 UTC
In ConfigMgr v2002, the computer restart settings do not match this documentation.  No reference to the updated restart settings is made in the What's New in version 2002, 1910, nor any tech preview release notes.
The updated language varies substantively from what existed in v1906.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c666f0e-89a1-dbe2-af7d-700a46aeea61
* Version Independent ID: 774f99b8-9403-1c77-abe5-54934f0d2f71
* Content: [Client settings - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/clients/deploy/about-client-settings#computer-restart)
* Content Source: [memdocs/configmgr/core/clients/deploy/about-client-settings.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/clients/deploy/about-client-settings.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment] 2020-05-21 23:52
Thanks @ChadSimmons for the feedback. We're tracking this via a work item (7182335) in our internal Azure DevOps system. I'll take a note to comment back here when the work is done.

Dupe of #228

**Closed by aczechowski** 2020-05-21 23:52 UTC
Labels: Pri1, configmgr-client/tech, configuration-manager/prod, duplicate

**Comment by aczechowski** [comment] 2020-06-02 19:56
For this article, I removed the computer restart settings and centralized all of it in the [device restart notifications](https://docs.microsoft.com/mem/configmgr/core/clients/deploy/device-restart-notifications#feedback) article. For that article, I revised and revamped, included some examples from engineering. I expect the revision to publish live tomorrow. Thanks again for the feedback!
