### ISSUE TITLE
Old Azure App Registration informations

### ISSUE THREAD

**Issue by Kreism** [MicrosoftDocs/memdocs#1451] opened 2021-03-26 13:32 UTC
Could you please update the Documentation about Registering the app?
Looks like some parts are not actual, like
**Type: Select Public client (mobile & desktops)**
There ist no such type anymore.
Thanks
Martin

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5da6c8b-447a-d0c7-4243-095745d85306
* Version Independent ID: 64b13b3d-22b4-2f04-0a7d-7d34a7b62395
* Content: [Manually register Azure AD apps - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/clients/manage/cmg/manually-register-azure-ad-apps)
* Content Source: [memdocs/configmgr/core/clients/manage/cmg/manually-register-azure-ad-apps.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/clients/manage/cmg/manually-register-azure-ad-apps.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment] 2021-04-14 01:01
Thanks @Kreism for the feedback. This issue is a duplicate of #1417.

**Closed by aczechowski** 2021-04-14 01:01 UTC
Labels: Pri2, configmgr-client/tech, configuration-manager/prod, duplicate
