### ISSUE TITLE
Different behavior than described for client using SUP that isn't in the client's boundary group.

### ISSUE THREAD

**Issue by davidpaMSFT** [MicrosoftDocs/memdocs#594] opened 2020-08-06 22:25 UTC
I am seeing different behavior than what is described here:

> Clients that already have a software update point continue to use it until it can't be reached. This **behavior includes continued use of a software update point that isn't associated with the client's current boundary group**.
> This behavior is intentional. **The client continues to use an existing software update point, even when it isn't in the client's current boundary group**.

https://docs.microsoft.com/en-us/mem/configmgr/core/servers/deploy/configure/boundary-groups#clients-continue-to-use-a-last-known-good-software-update-point-until-they-fallback-to-find-a-new-one

What I am seeing is that if SUP that client is currently using is removed from client’s current boundary group (or fallback), the client will switch to another SUP from the list it gets in WSUSLocationReply. If there are no other SUPs, it will not (be able to) perform the scan at all. Either way, **it does not continue using the existing SUP if that SUP is removed from client’s boundary group** and therefore no longer returned in WSUSLocation reply.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a2d3a58-d1b9-6f56-8f0c-dfdf2733b670
* Version Independent ID: 436c5f30-086a-5c8a-d9b3-98a017f9f55b
* Content: [Configure boundary groups - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/servers/deploy/configure/boundary-groups)
* Content Source: [memdocs/configmgr/core/servers/deploy/configure/boundary-groups.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/servers/deploy/configure/boundary-groups.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by mestew** [comment] 2021-04-27 21:14
Yeah. That part of the article hasn't been updated since 1702 where we introduced all these changes. I dug through the article's history, and it needs a revamp. I am filing an internal doc item (9812053) to review this article for accuracy and to possibly break it up.  Closing this as duplicate of internal doc item.

**Closed by mestew** 2021-04-27 21:14 UTC
Labels: Pri2, configmgr-core/tech, configuration-manager/prod, triaged
