### ISSUE TITLE
Incorrect registry path

### ISSUE THREAD

**Issue by DaravuthL** [MicrosoftDocs/memdocs#433] opened 2020-06-26 09:22 UTC
[Enter feedback here]
3. Navigate through the nested menus to SOFTWARE > Policies > Microsoft Windows Defender > Policy Manager
should be
3. Navigate through the nested menus to SOFTWARE > Policies > Microsoft > Windows Defender > Policy Manager 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b24a11cd-2a69-4dea-1153-7b769ab61101
* Version Independent ID: ed855316-fc81-7986-f02d-dd07baaee300
* Content: [How to protect your Windows device with encryption](https://docs.microsoft.com/en-us/mem/intune/user-help/encrypt-your-device-windows)
* Content Source: [memdocs/intune/user-help/encrypt-your-device-windows.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/user-help/encrypt-your-device-windows.md)
* Service: **microsoft-intune**
* Sub-service: **end-user**
* Product: ****
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by jpcast88** [comment] 2020-07-29 02:28
> 3. Navigate through the nested menus to SOFTWARE > Policies > Microsoft Windows Defender > Policy Manager

@DaravuthL I'm not seeing the line that you mentioned for the Content article that's referenced by this PR. Did you mean this article instead? https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/enable-network-protection#check-if-network-protection-is-enabled

**Comment by lenewsad** [comment] 2020-08-25 00:00
Hi @DaravuthL, thank you for your contribution. It looks like you're referring to the instructions in this article: https://docs.microsoft.com/windows/security/threat-protection/microsoft-defender-atp/enable-network-protection#check-if-network-protection-is-enabled

 I confirmed that there is an arrow missing between **Microsoft** and **Windows Defender** and submitted a request to change this. Here is the PR: https://github.com/MicrosoftDocs/windows-itpro-docs/pull/8131 

I am closing this issue as there are no changes that need to be made to the Intune article.

**Closed by lenewsad** 2020-08-25 00:00 UTC
Labels: /prod, /tech, Pri2, doc-enhancement, end-user/subsvc, in-progress, microsoft-intune/svc, triaged
