### ISSUE TITLE
Use Primary device from Intune in SCCM

### ISSUE THREAD

**Issue by TiganSan** [MicrosoftDocs/memdocs#251] opened 2020-05-15 17:41 UTC
I have come across a number of references that say the Primary user assignment in Intune can be synched/used in SCCM to set device affinity and link the user to the same device in SCCM.  However, I am not able to find any documentation on how to accomplish this?
All of our windows 10 devices are registered in Intune and have a Primary User assigned.  All user and devices accounts are also in SCCM (we are in co-managed mode).  How do I bring this info from Intune into SCCM?
Thx

**Comment by aczechowski** [comment] 2020-05-15 23:35
I'm checking with a PM on this

**Comment by aczechowski** [comment] 2020-05-18 23:33
Hi @TiganSan. Thanks for taking the time to provide feedback on Configuration Manager and Intune! I confirmed with the PMs that this is not possible today. Can you share the "number of references" that you mention?

Otherwise, it's best to file as product feedback to the engineering team. See the [ConfigMgr product feedback](https://docs.microsoft.com/mem/configmgr/core/understand/find-help#product-feedback) article. For Intune, go directly to the [Intune UserVoice site](https://microsoftintune.uservoice.com/). I think it’s important that you submit it directly, because that allows you to receive notifications and more closely monitor the progress. I'm closing this issue as there's nothing actionable for docs at this time.

**Closed by aczechowski** 2020-05-18 23:33 UTC
Labels: Pri3, product-feedback, triaged

**Comment by maheDJ** [comment] 2023-06-23 07:20
> I confirmed with the PMs that this is not possible today.

@aczechowski and today? still not possible?
