### ISSUE TITLE
Inconsistent with what Apple states in their documentation and Intune functionality

### ISSUE THREAD

**Issue by OffColour** [MicrosoftDocs/memdocs#2810] opened 2022-05-25 12:41 UTC
So this page states that enrolling your device gives the company the ability reset your phone to factory whereas when you go through the setup process on iOS it explicitly states that the company can't and the "wipe" button is disabled in Intune for personal devices.

It also contradicts what is in this Apple document [https://www.apple.com/business/docs/resources/Managing_Devices_and_Corporate_Data_on_iOS.pdf](https://www.apple.com/business/docs/resources/Managing_Devices_and_Corporate_Data_on_iOS.pdf)

Combine that with disabling the camera and blocking web browsing and this page is putting our users off installing the portal on their personal devices. If this only applies to compnay managed devices then it should be clear about that and have separate pages for what can be done to corporate devices and what can be done to a personal device.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3670cad-3065-cb6f-f8d3-1b4e702e0ad8
* Version Independent ID: c72cd280-2688-b5cb-e894-e82c93272f94
* Content: [Installing the Company Portal app for iOS](https://docs.microsoft.com/en-us/mem/intune/user-help/what-happens-if-you-install-the-company-portal-app-and-enroll-your-device-in-intune-ios)
* Content Source: [memdocs/intune/user-help/what-happens-if-you-install-the-Company-Portal-app-and-enroll-your-device-in-intune-ios.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/user-help/what-happens-if-you-install-the-Company-Portal-app-and-enroll-your-device-in-intune-ios.md)
* Service: **microsoft-intune**
* Sub-service: **end-user**
* Product: ****
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by yogkumgit** [comment] 2022-05-31 07:48
@lenewsad Please help us in resolving this issue. Thanks

**Comment by lenewsad** [comment] 2022-07-08 19:01
Hi @OffColour, thank you for reaching out with your questions. Let me reach out to our product team for more clarification. Can you please provide a little more info for me?  
 
* This is the article your comment is on, so want to make sure it's the one you intended. https://docs.microsoft.com/en-us/mem/intune/user-help/use-managed-devices-to-get-work-done Please confirm. 
* I don't see where it mentions that the company can wipe the device. I do see this section: https://docs.microsoft.com/en-us/mem/intune/user-help/use-managed-devices-to-get-work-done#can-you-remove-a-device-from-the-company-portal  Which tells employees/students how to remove or reset the device they're using. Is this where the issue is? 

As for blocking camera/web browsing--I am updating this page to clarify that those policies can only be enforced when the device user is signed in to a work or school app on their device, or when using a corporate-owned device. 

FYI @yogkumgit

**Comment by OffColour** [comment] 2022-07-08 21:46
Hi @lenewsad
This page has completely changed since I raised it.
The source link in my OP now gives a 404 and the page I originally commented on was called "Installing the company portal app on iOS."

I still think there is a fundamental problem with Intune mobile device documentation in that in combines corporate owned and BYOD information on the same pages.

As an Intune admin I want my users to feel comfortable that using their personal devices for work purposes in no way compromises their privacy or their control over their devices.

The Intune documentation fails to do this as users will Google this information, read the pages on Intune see the level of control admins have over corporate owned devices and get worried.

I'd also say that the end user documentation is too complicated. They want to see simple pages (one for Android and one for iOS) stating exactly what their company can and cannot do to their device once they install company portal.

**Closed** 2022-07-11 14:52 UTC
Labels: microsoft-intune/svc, /tech, Pri1, end-user/subsvc, /prod, writer-input-required
