### ISSUE TITLE
iOS compliance policy

### ISSUE THREAD

**Issue by kevintaber** [MicrosoftDocs/memdocs#2069] opened 2021-10-07 03:10 UTC
This document mentions the wording “passcode” for iOS compliance policies. However, the wording within MEM is “password”.

So when an iOS compliance policy has the Password option set to Required, it forces users to change from a passcode (PIN) to a password.

I don’t see how I can require an actual passcode (PIN), not a password, like Apple does when Face ID or Touch ID is enabled.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 627e68f4-967b-9c95-abfe-da94f946af5a
* Version Independent ID: 2633cc4a-dc50-8f7a-9bf6-a3718a61928c
* Content: [Password requirements for Intune-enrolled devices](https://docs.microsoft.com/en-us/mem/intune/user-help/password-does-not-meet-it-administrator-requirements)
* Content Source: [memdocs/intune/user-help/password-does-not-meet-it-administrator-requirements.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/user-help/password-does-not-meet-it-administrator-requirements.md)
* Service: **microsoft-intune**
* Sub-service: **end-user**
* Product: ****
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by msbemba** [comment] 2022-03-13 19:38
@kevintaber Thank you for your feedback. I'm not able to reproduce the issue. I think this could be due to another passcode requirement like it must contain alphanumeric characters or Passcode must contain non-alphanumeric characters etc. From my testing, it forces to change the password when there is another policy requirement set in the organization. 

If this is not the case, I'd recommend you contact Support via the need help option on the admin center.

Hope this helps!

Thanks
Sir

**Comment by yogkumgit** [comment] 2022-03-14 13:12
@msbemba Thank you very much for the contribution and sharing this explanation. @kevintaber Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Closed by yogkumgit** 2022-03-14 13:12 UTC
Labels: microsoft-intune/svc, /tech, Pri1, support-request, end-user/subsvc, /prod
