### ISSUE TITLE
Maximum size of intunemac file ?

### ISSUE THREAD

**Issue by vadivelub** [MicrosoftDocs/memdocs#1174] opened 2020-12-31 14:45 UTC
As per the documentation, Intunemac will support upto 2 GB of file.  when we try to upload 2 GB , we are getting unexpected error. Please clarify what is the maximum size of intunemac file that supported by Intune?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54e4efd6-d1de-dba7-6ae5-a91c7a28b662
* Version Independent ID: f529438b-becd-3b8e-dc6c-02413af9854f
* Content: [How to add macOS line-of-business apps to Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/lob-apps-macos)
* Content Source: [memdocs/intune/apps/lob-apps-macos.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/lob-apps-macos.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by Erikre** [comment] 2021-02-18 22:48
Thanks for the feedback. I'm tracking this issue using an internal work item and I'm requesting feedback from the product team.  We do mention the iOS file size limit as 2 GB per app, but I am working on confirming the size limit for macOS. Once I have confirmed this, I'll update the topic. If you have continue to have questions related to this issue, we want to make sure your questions get to the right people that can help. There are a couple of options available to provide the best level of support for this:

- Post your issue on [Microsoft Intune forums](https://social.technet.microsoft.com/Forums/en-US/home?forum=microsoftintuneprod). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.

- Use [How to get support for Microsoft Intune](https://docs.microsoft.com/intune/get-support) to open a case with professional support.

- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.

Please use the above channels if you don't already have a solution. Because I'm tracking any doc updates based on an internal work item, I'm closing this GitHub issue. Thanks

**Closed by Erikre** 2021-02-18 22:48 UTC
Labels: /tech, Pri1, apps/subsvc, microsoft-intune/svc, pm, tracking-as-internal-work-item
