### ISSUE TITLE
Screenshot contains incorrect information

### ISSUE THREAD

**Issue by jordanvrij** [MicrosoftDocs/memdocs#1214] opened 2021-01-13 15:17 UTC
Image **apps-win32-app-05.png** is incorrect. It should show: HKEY_LOCAL_MACHINE\Software\WinRAR instead of **Computer\**HKEY_LOCAL_MACHINE\Software\WinRAR. The corresponding text example above the image _is_ correct. Verified on my Intune environment. Probably a sloppy copy/paste job from regedit (which does use Computer\).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca840cce-3b99-3009-c8fa-d5fab6ae37d0
* Version Independent ID: 928b9e37-626a-8d50-c6a1-ac0b5cad4be4
* Content: [Add and assign Win32 apps to Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/apps-win32-add)
* Content Source: [memdocs/intune/apps/apps-win32-add.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/apps-win32-add.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by Erikre** [comment] 2021-02-18 21:42
@jordanvrij - Thanks for the feedback. I'm tracking this issue using an internal work item and requesting confirmation from the product team. Once I have confirmed the change, I'll update the topic. If you have continue to have questions related to this issue, we want to make sure your questions get to the right people that can help. There are a couple of options available to provide the best level of support for this:

- Post your issue on [Microsoft Intune forums](https://social.technet.microsoft.com/Forums/en-US/home?forum=microsoftintuneprod). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.

- Use [How to get support for Microsoft Intune](https://docs.microsoft.com/intune/get-support) to open a case with professional support.

- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.

Please use the above channels if you don't already have a solution. I'm closing this GitHub issue because I'm tracking it internally. Thanks

**Closed by Erikre** 2021-02-18 21:42 UTC
Labels: /tech, Pri1, apps/subsvc, microsoft-intune/svc, pm, tracking-as-internal-work-item
