### ISSUE TITLE
Password expiration (days) applicability 

### ISSUE THREAD

**Issue by Dpovea** [MicrosoftDocs/memdocs#2306] opened 2021-12-20 19:01 UTC
[Enter feedback here]
when "Password expiration (days)" is described it's stated is only applicable for Android 9 or older devices. Should this setting be considered as non applicable for Android 10, 11 or 12 devices enrolled with the same Work profile and required to set a PIN with at least 6 characters long? 
Is it possible to disable this setting or set longer than 365 days? iOS Password expiration allows up to 1000 days instead. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a95bbc4-3e4d-3f04-fb25-d41d7b6e3c73
* Version Independent ID: 7dbbb2c0-8c34-a5aa-dd4a-cc5b0afe5180
* Content: [Device restriction settings for Android in Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/configuration/device-restrictions-android)
* Content Source: [memdocs/intune/configuration/device-restrictions-android.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/configuration/device-restrictions-android.md)
* Service: **microsoft-intune**
* Sub-service: **configuration**
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by msbemba** [comment] 2022-03-24 12:50
@Dpovea Thank you for your feedback. By design, the Password expiration (days) must be between 1-365 days and is applicable only for Android 9 and earlier, or Samsung Knox (any version). It is not applicable for Android 10 and later.

Hope this helps!

Thanks
Sri

**Comment by msbemba** [comment] 2022-03-31 11:31
@yogkumgit The document is updated and this can be closed.

**Comment by yogkumgit** [comment] 2022-03-31 13:43
@msbemba Thank you very much for the contribution and sharing this explanation. @Dpovea Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Closed by yogkumgit** 2022-03-31 13:43 UTC
Labels: doc-enhancement, microsoft-intune/svc, Pri1, configuration/subsvc
