### ISSUE TITLE
Missing configuration

### ISSUE THREAD

**Issue by gilbertmcx** [MicrosoftDocs/memdocs#392] opened 2020-06-18 12:25 UTC
When running the prerequisite check it told me to install WSUS which is not shown. I believe there are a couple more components missing but can't recall which ones. Would be nice to have the website updated and even the software updated since Windows Server 2019 and SQL Server 2019 are out.

**Comment by ErikjeMS** [comment] 2020-06-22 16:56
@gilbertmcx Can you provide a link to the article that this refers to?

**Comment by gilbertmcx** [comment] 2020-06-22 17:31
When launching the pre requisite checker prior the System Center installation, it says it requires WSUS installed.
This is the website where I consider WSUS requirement is missing: https://docs.microsoft.com/en-us/mem/configmgr/core/get-started/set-up-your-lab

**Comment by aczechowski** [comment] 2020-06-25 22:46
Thanks @gilbertmcx for the feedback. I'm going to close this issue as a duplicate of #159. You can subscribe to that issue to get updates on progress.

**Closed by aczechowski** 2020-06-25 22:46 UTC
Labels: Pri3, duplicate
