### ISSUE TITLE
PackageManagement\Install-Package : No match was found for the specified search criteria and script name

### ISSUE THREAD

**Issue by bubba198** [MicrosoftDocs/memdocs#1292] opened 2021-02-03 03:08 UTC
As expected:

WARNING: Unable to resolve package source 'https://www.powershellgallery.com/api/v2/items/psscript'.
PackageManagement\Install-Package : No match was found for the specified search criteria and script name
'Get-WindowsAutoPilotInfo'. Try Get-PSRepository to see all available registered script repositories.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:3500 char:21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package], Ex
   ception
    + FullyQualifiedErrorId : NoMatchFoundForCriteria,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea4a659b-65d0-26ec-c36a-9a21a72a09a8
* Version Independent ID: bff44b73-9021-6659-e212-66349c759989
* Content: [Manually register devices with Windows Autopilot](https://docs.microsoft.com/en-us/mem/autopilot/add-devices)
* Content Source: [memdocs/autopilot/add-devices.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/autopilot/add-devices.md)
* Product: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by frankroj** [comment] 2023-04-27 00:33
Thank you for the feedback @bubba198. I apologize for the time it took to get back to you regarding this feedback item. I was able to run the scripts successfully from my end. With that said, there have been some updates to the scripts since you filed this feedback item. I would suggest trying again to see if the problem is resolved.

if it doesn't resolve the problem, I’m sorry that you’re continuing to have problems, but I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this issue:

- Post to [Microsoft](https://learn.microsoft.com/answers/tags/415/intune). These are moderated by community members who are very experienced, knowledgeable, and helpful.
- Use [Windows Autopilot support information](https://support.microsoft.com/windows) to find your available support options.
- Contact your Microsoft Unified Support team, such as a Customer Engineer or Customer Success Account Manager.

I'm closing this issue as there's nothing actionable for docs at this time.

**Closed by frankroj** 2023-04-27 00:33 UTC
Labels: Pri1, w10/prod
